<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InsertEmployees extends Seeder
{
    public function run()
    {
        $values = [
            [
                'id' => 1,
                'name' => 'Hj. Nanik Herlinawati, M.Pd',
                'type' => 'teacher',
                'position' => 'Kepala Sekolah',
                'education' => 'S2 - Manajemen Pendidikan',
                'year_graduated' => 2016,
                'photo' => 'nanik.webp',
                'description' => null,
                'slug' => 'nanik-herlinawati',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Aep Saepudin, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru Kelas 4A',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2006,
                'photo' => 'aep.webp',
                'description' => null,
                'slug' => 'aep-saepudin',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Sapariyah, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru Kelas 3A',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2015,
                'photo' => 'sapariyah.webp',
                'description' => null,
                'slug' => 'sapariyah',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Rohmat Nasrul Hidayat, S.Pd.I',
                'type' => 'teacher',
                'position' => 'Guru Kelas 5B',
                'education' => 'S1 - PAI',
                'year_graduated' => 2004,
                'photo' => 'rohmat.webp',
                'description' => null,
                'slug' => 'rohmat-nasrul-hidayat',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Musliman, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru Kelas 4B',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2015,
                'photo' => 'musliman.webp',
                'description' => null,
                'slug' => 'musliman',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Kusniyati, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru Kelas 6B',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2006,
                'photo' => 'kusniyati.webp',
                'description' => null,
                'slug' => 'kusniyati',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Saroh Wijiastuti, S.Pd.SD',
                'type' => 'teacher',
                'position' => 'Guru Kelas 1A & 2A',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2011,
                'photo' => 'saroh.webp',
                'description' => null,
                'slug' => 'saroh-wijiastuti',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Hestiani, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru Kelas 5B',
                'education' => 'S1 - PPKn',
                'year_graduated' => 2013,
                'photo' => 'hestiani.webp',
                'description' => null,
                'slug' => 'hestiani',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Heni Widyana, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru Kelas 1C & 2C',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2018,
                'photo' => 'heni.webp',
                'description' => null,
                'slug' => 'heni-widyana',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Silviyatun, S.Pd.I',
                'type' => 'teacher',
                'position' => 'Guru PAI Kelas 4-6',
                'education' => 'S1 - Kependidikan Islam',
                'year_graduated' => 2004,
                'photo' => 'silviyatun.webp',
                'description' => null,
                'slug' => 'silviyatun',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Marina Sarrizki, S.Pd',
                'type' => 'teacher',
                'position' => 'Guru Kelas',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2004,
                'photo' => 'marina.webp',
                'description' => null,
                'slug' => 'marina-sarrizki',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Romadhona Aidin, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru PJOK Kelas 1-3',
                'education' => 'S1 - PJOK',
                'year_graduated' => 2015,
                'photo' => 'romadhona.webp',
                'description' => null,
                'slug' => 'romadhona-aidin',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'Intan Prawesti, S.Pd',
                'type' => 'teacher',
                'position' => 'Guru Kelas',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2011,
                'photo' => 'intan.webp',
                'description' => null,
                'slug' => 'intan-prawesti',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Adnan Zaki, S.Kom',
                'type' => 'staff',
                'position' => 'Staff Keuangan Bid. Keuangan',
                'education' => 'S1 - Teknik Informatika',
                'year_graduated' => 2018,
                'photo' => 'adnan.webp',
                'description' => null,
                'slug' => 'adnan-zaki',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Darmanto, S.Pd.I',
                'type' => 'teacher',
                'position' => 'Guru PAI Kelas 1-3',
                'education' => 'S1 - PAI',
                'year_graduated' => 2012,
                'photo' => 'darmanto.webp',
                'description' => null,
                'slug' => 'darmanto',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Rina Rosinta, S.Pd',
                'type' => 'teacher',
                'position' => 'Guru Kelas',
                'education' => 'S1 - PGSD',
                'year_graduated' => 2024,
                'photo' => 'rina.webp',
                'description' => null,
                'slug' => 'rina-rosinta',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'M. Insan Maulana Ibrahim, S.A.p',
                'type' => 'staff',
                'position' => 'Staff Keuangan Bid. Kesiswaan dan Kepegawaian',
                'education' => 'S1 - Administrasi Publik',
                'year_graduated' => 2022,
                'photo' => 'insan.webp',
                'description' => null,
                'slug' => 'insan-maulana-ibrahim',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Fahrianto, S.Pd.',
                'type' => 'teacher',
                'position' => 'Guru PJOK Kelas 4-6',
                'education' => 'S1 - PJOK',
                'year_graduated' => 2021,
                'photo' => 'fahrianto.webp',
                'description' => null,
                'slug' => 'fahrianto',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'Suci Khamila Dewi',
                'type' => 'teacher',
                'position' => 'Guru Kelas',
                'education' => 'SMK',
                'year_graduated' => 2019,
                'photo' => 'suci.webp',
                'description' => null,
                'slug' => 'suci-khamila-dewi',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Mohamad Sholeh',
                'type' => 'staff',
                'position' => 'Petugas Kebersihan',
                'education' => 'SD',
                'year_graduated' => 1988,
                'photo' => 'mohamad.webp',
                'description' => null,
                'slug' => 'mohamad-sholeh',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Muhammad Jamatullail Siraj',
                'type' => 'staff',
                'position' => 'Pustakawan',
                'education' => 'SMK',
                'year_graduated' => 2025,
                'photo' => 'muhammad.webp',
                'description' => null,
                'slug' => 'muhammad-jamatullail-siraj',
                'created_at' => '2026-04-30 14:35:00',
                'updated_at' => '2026-04-30 14:35:00',
                'deleted_at' => null,
            ],
        ];

        $this->db->table('p7_employees')->insertBatch($values);
    }
}
